### 06 ``numpy.array`` 合并与分割

In [1]:
import numpy as np

#### numpy.array的合并

In [2]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y]) # 将x,y合并成一个列表

array([1, 2, 3, 3, 2, 1])

In [4]:
z=np.array([666,666,666])
np.concatenate([x,y,z]) # 将x,y,z合并成一个列表

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [5]:
A = np.array([[1,2,3],
             [4,5,6]])
np.concatenate([A,A])  #将两个矩阵合并

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
np.concatenate([A,A],axis=1)  #将两个矩阵合并, 以列为准

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [7]:
np.concatenate([A,z])  #A与z的维度不一样

ValueError: all the input arrays must have same number of dimensions

In [10]:
z.reshape(1,-1)


array([[666, 666, 666]])

In [11]:
np.concatenate([A,z.reshape(1,-1)])  # 改变z的形状,可以与A合并

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [12]:
np.vstack([A,z]) #同上, 垂直, 合并

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [13]:
B = np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [14]:
np.hstack([A,B])  #水平,合并

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [15]:
np.hstack([A,z]) # 维度不相同

ValueError: all the input arrays must have same number of dimensions

### ``numpy.array``的分割

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x1,x2,x3 = np.split(x,[3,7])  # 分割成三份,  0-3, 3,-7,7-结束

In [20]:
x1,x2,x3

(array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9]))

In [21]:
x1,x2 = np.split(x,[5])

In [22]:
x1,x2

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [24]:
A = np.arange(16).reshape((4,4)) # 生成16个数字, 并改变形状 4,4
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
A1,A2 = np.split(A,[2]) # 按2行分割, 上下分割

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [29]:
A1,A2 = np.split(A,[2],axis=1) #按2列分割, 左右分割

In [30]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [31]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [35]:
upper,lower = np.vsplit(A,[2])  # 上下分割

In [33]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
left,right = np.hsplit(A,[2]) # 左右分割

In [37]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [38]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

### 特征工程常用的, 取出最后一列数据

In [39]:
data = np.arange(16).reshape((4,4))  # 生成一个4x4的矩阵

In [40]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
X,y = np.hsplit(data,[-1])  # 按最后一列分割

In [43]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [44]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [46]:
y[:,0]  # 读取矩阵所有行, 再读取第一列, 改变成向量,

array([ 3,  7, 11, 15])