### 09 `Numpy`中arg运算

In [2]:
import numpy as np

In [7]:
x=np.random.normal(0,1,1000000)

索引

In [8]:
np.argmin(x) #最小值所在的索引??

311895

In [10]:
x[np.argmin(x)] # 使用最小值的索引,读取最小值

-5.443462991275668

In [12]:
np.min(x) # 同上面的代码, 结果一致

-5.443462991275668

In [13]:
np.argmax(x)#最大值所在的索引??

651111

In [14]:
np.max(np.argmax(x))# 同上面的代码, 结果一致

651111

### 排序和使用索引

In [15]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
np.random.shuffle(x) #将数组打乱随机排列
x

array([ 2, 10,  9,  6,  7,  5, 14,  8, 13, 15,  3, 12, 11,  1,  4,  0])

In [19]:
np.sort(x) #再从小到大的排序

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
x

array([ 2, 10,  9,  6,  7,  5, 14,  8, 13, 15,  3, 12, 11,  1,  4,  0])

In [22]:
x.sort()
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
X = np.random.randint(10,size=(4,4))
X

array([[0, 2, 1, 2],
       [0, 8, 6, 5],
       [6, 8, 2, 7],
       [8, 1, 4, 2]])

In [24]:
np.sort(X,axis=0)

array([[0, 1, 1, 2],
       [0, 2, 2, 2],
       [6, 8, 4, 5],
       [8, 8, 6, 7]])

In [25]:
np.sort(X, axis=1)

array([[0, 1, 2, 2],
       [0, 5, 6, 8],
       [2, 6, 7, 8],
       [1, 2, 4, 8]])

#### 使用索引

In [26]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
np.random.shuffle(x)
x

array([14,  5, 15, 12,  1,  8,  4,  2, 11,  3, 10,  9,  6,  7, 13,  0])

In [29]:
np.argsort(x)

array([15,  4,  7,  9,  6,  1, 12, 13,  5, 11, 10,  8,  3, 14,  0,  2],
      dtype=int64)

In [31]:
np.partition(x, 3) # 分区排序

array([ 1,  0,  2,  3,  4,  5,  6,  8, 11,  7, 10,  9, 12, 15, 13, 14])

In [32]:
np.argpartition(x, 3)

array([ 4, 15,  7,  9,  6,  1, 12,  5,  8, 13, 10, 11,  3,  2, 14,  0],
      dtype=int64)

In [33]:
X

array([[0, 2, 1, 2],
       [0, 8, 6, 5],
       [6, 8, 2, 7],
       [8, 1, 4, 2]])

In [34]:
np.argsort(X, axis=1)  #索引

array([[0, 2, 1, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1],
       [1, 3, 2, 0]], dtype=int64)

In [35]:
np.argpartition(X, 2, axis=1)

array([[0, 2, 1, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1],
       [1, 3, 2, 0]], dtype=int64)