## 05 ``numpy.array``基本操作

In [2]:
import numpy as np
np.random.seed(0)
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
X = np.arange(15).reshape((3,5)) #转换成3行5列的矩阵
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### ``numpy.array`` 的基本属性

In [7]:
x.ndim # 维度

1

In [8]:
X.ndim

2

In [10]:
x.shape # 形状

(10,)

In [11]:
X.shape

(3, 5)

In [12]:
x.size #大小,元素个数

10

In [13]:
X.size

15

### ``numpy.array``的数据访问

In [14]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[0]

0

In [16]:
x[-1]

9

In [17]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
X[0][0] #不建议这样的访问元素

0

In [19]:
X[0,0]

0

In [20]:
X[0,-1]

4

In [21]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[0:5]

array([0, 1, 2, 3, 4])

In [23]:
x[:5] #从index=0开始,直到index=5

array([0, 1, 2, 3, 4])

In [25]:
x[5:]  #从index=5开始,直到结束

array([5, 6, 7, 8, 9])

In [26]:
x[4:7]

array([4, 5, 6])

In [27]:
x[::2] # 步长是2

array([0, 2, 4, 6, 8])

In [28]:
x[::-1]  # 倒序

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
X   #矩阵

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
X[:2,:3]   # 读取  第0, 1行, 等0,1,2列

array([[0, 1, 2],
       [5, 6, 7]])

In [32]:
X[:2][:3]  # 结果不一样,在numpy中使用","做多维索引

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
X[:2,::2]  #读取 0,1 行,每两列读取一下列元素

array([[0, 2, 4],
       [5, 7, 9]])

In [34]:
X[::-1,::-1]  # 行列倒序

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [35]:
X[0,:] # 读取等一行

array([0, 1, 2, 3, 4])

In [36]:
X[:,0] # 读取所有行的第一列元素

array([ 0,  5, 10])

### Subarray of ``numpy.array``   子数组

In [40]:
subX = X[:2,:3]  #subX是X的子数组, 但底层是同一组数据
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [41]:
subX[0,0] = 100 # 也会影响X[0,0]
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [43]:
X  # 其中[0,0]元素被subX[0,0]的修改,影响

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [44]:
X[0,0] = 0 # 也会影响subX[0,0], 双方是对应同一个数据
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

### 使用.copy

In [46]:
subX = X[:2,:3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [48]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [50]:
X #不会受到subX的影响

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [51]:
x.shape

(10,)

In [53]:
x.ndim

1

In [54]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
A=x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [59]:
B.ndim

2

In [60]:
B.shape

(1, 10)

In [61]:
x.reshape(-1,10) #自动推算

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
x.reshape(10,-1)#自动推算

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [63]:
x.reshape(2,-1) #自动推算

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
x.reshape(3,-1) # 因为x只有10个元素, 无法排放成3的倍数的矩阵

ValueError: cannot reshape array of size 10 into shape (3,newaxis)