## 03 numpy.array 基础

In [80]:
import numpy

In [81]:
numpy.__version__

'1.15.1'

In [82]:
import numpy as np  #简写
np.__version__

'1.15.1'

## Python List的特点

In [83]:
L=[i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
L[5]

5

In [85]:
L[5] =100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [86]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

### Python的list不要求存储同样的类型,带来效率问题

In [87]:
import array
arr = array.array("i",[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr[5]

5

In [89]:
arr[5]=100
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [90]:
# 类型不正确
# arr[5] = "Machine Learning"

In [91]:
 # 类型不正确
# arr[5] = 5.0 

## array的缺点是没有将数据当做向量或者矩阵, 不支持基本运算

## numpy.array

### int

In [92]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
nparr[5] = 100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [94]:
# 类型不正确
# nparr[5] = "Machine Learning"

In [95]:
nparr.dtype  #查看元素的数据类型

dtype('int32')

In [96]:
nparr[5] = 5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
nparr.dtype

dtype('int32')

In [98]:
nparr[5] = 3.14  #自动去掉小数点部分
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

###  float

In [99]:
nparr2 = np.array([1,2,3.0])
nparr2

array([1., 2., 3.])

In [100]:
nparr2.dtype

dtype('float64')