### 08 ``Numpy``中的聚合操作

### `sum`

In [2]:
import numpy as np
L=np.random.random(100)
sum(L)

50.0205044590344

In [3]:
np.sum(L)

50.020504459034406

In [5]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)   #np的性能更高

299 ms ± 123 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.73 ms ± 460 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### min,max

In [6]:
np.min(big_array)

2.4185192282200063e-06

In [7]:
np.max(big_array)

0.9999995382364816

In [8]:
big_array.min()

2.4185192282200063e-06

In [9]:
big_array.max()

0.9999995382364816

In [10]:
big_array.sum()

499716.16030919016

### 多维度聚合

In [11]:
X = np.arange(16).reshape(4,-1)  #4维方阵
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
np.sum(X)

120

In [13]:
np.sum(X,axis=0) #横向

array([24, 28, 32, 36])

In [14]:
np.sum(X,axis=1) # 纵向

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作, 中位数, 平均值, 标准差, 均方差, 乘积

In [15]:
np.prod(X) #函数用来计算所有元素的乘积

0

In [16]:
np.prod(X+1) #函数用来计算所有元素的乘积

2004189184

In [17]:
np.mean(X)  #np.mean 总是计算算术平均值

7.5

In [18]:
np.median(X) #中位数

7.5

In [19]:
v = np.array([1,1,2,2,10]) 
np.mean(v) #平均值

3.2

In [20]:
np.median(v)

2.0

In [22]:
 #np.percentile()函数的作用就是求百分位数，从而能够知道数字大致的分布
np.percentile(big_array, q=50)

0.4997951268372251

In [23]:
np.median(big_array)

0.4997951268372251

In [24]:
np.percentile(big_array, q=100)

0.9999995382364816

In [25]:
np.max(big_array)

0.9999995382364816

In [26]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

2.4185192282200063e-06
0.24944095663628923
0.4997951268372251
0.7496886131414358
0.9999995382364816


In [27]:
np.var(big_array)  #均方差

0.08340446561571238

In [28]:
np.std(big_array) #标准差 np.std()的平方等于np.var()

0.2887983130416665

In [29]:
x = np.random.normal(0, 1, 1000000)

In [30]:
np.mean(x)

0.00047397095333976525

In [31]:
np.std(x)

0.998445782021331