## 04 创建numpy.array

In [1]:
import numpy as np

`numpy.array`

In [2]:
# 创建一维数组
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 其他创建 `numpy.array`的方法

### ``zeros``

In [3]:
np.zeros(10)  #默认类型是 float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.zeros(10).dtype

dtype('float64')

In [5]:
np.zeros(10,dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# 创建二维数据(矩阵)
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.zeros(shape=(3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### ``ones``

In [10]:
np.ones(10) #默认类型是 float

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.ones(shape=(3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### ``full``

In [14]:
np.full((3,5),666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [15]:
np.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### ``arange``

In [16]:
[i for i in range (0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [17]:
np.arange(0,20,2)  # 2是步长

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# py的步长, 不支持小数
[i for i in range(0,1,0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [20]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [21]:
[i for i in range(0,10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### ``linspace``

In [26]:
np.linspace(0,20,10)  # 从0 到20 ,平均生成10个元素

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [27]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [28]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### ``random``

### ``randint``

In [29]:
np.random.randint(0,10) # [0 ,10 )之间的随机数, 生成一个

2

In [31]:
np.random.randint(0,10,10) # [0 ,10 )之间的随机数, 生成 10 个

array([5, 0, 0, 3, 0, 1, 5, 5, 8, 8])

In [32]:
np.random.randint(0,1,10) # [0 ,10 )之间的随机数, 生成 10 个 ,不包含 1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.random.randint(0,1,size=10) # [0 ,10 )之间的随机数, 生成 10 个 ,不包含 1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
np.random.randint(0,10,size=(3,5)) # [0 ,10 )之间的随机数, 生成 10 个 ,不包含 1

array([[8, 1, 7, 5, 9],
       [6, 7, 0, 3, 7],
       [4, 9, 1, 8, 5]])

In [36]:
np.random.randint(10,size=(3,5)) # [0 ,10 )之间的随机数, 生成 10 个 ,不包含 1

array([[0, 0, 2, 1, 6],
       [4, 9, 2, 2, 9],
       [0, 2, 4, 8, 3]])

### ``seed``

In [38]:
np.random.seed(666)

In [47]:
np.random.randint(0, 10, size=(3, 5))

array([[4, 4, 0, 0, 4],
       [0, 4, 5, 7, 1],
       [0, 0, 6, 6, 0]])

In [46]:
np.random.seed(666)
np.random.randint(0, 10, size=(3,5))  # 不变的随机数

array([[2, 6, 9, 4, 3],
       [1, 0, 8, 7, 5],
       [2, 5, 5, 4, 8]])

### ``normal``

In [49]:
np.random.normal() # 正态分布的随机数

0.8529015329736077

In [50]:
np.random.normal(10, 100)

29.459960304411826

In [54]:
np.random.seed(666)
np.random.normal(0, 1, (3, 5))

array([[ 0.82418808,  0.479966  ,  1.17346801,  0.90904807, -0.57172145],
       [-0.10949727,  0.01902826, -0.94376106,  0.64057315, -0.78644317],
       [ 0.60886999, -0.93101185,  0.97822225, -0.73691806, -0.29873262]])

`np.random.<TAB>` 查看random中的更多方法

In [56]:
np.random?

In [57]:
np.random.normal?

In [58]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap